params:
  seed: ${...seed}

  algo:
    name: a2c_discrete

  model:
    name: multi_discrete_transformer_a2c

  network:
    name: actor_critic_transformer
    separate: False
    space:
      multi_discrete:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    transformer:
      input_sequence_length: 8
      pos_embedding: learnt
      num_head: 2
      num_layer: 2
      dim_feedforward: 1024
      transforms_mlp_dim: [128, 128]
      state_mlp_dim: [128, 128]
      critic_mlp_dim: [512, 512, 256]
      fuse_mlp_dim: [128, 128]
      d_model: 128
      dropout: 0.0
      decoder_mlp_dim: [256, 256]
      embed_init: 0.1
      decoder_init: 0.01

      activation: tanh
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FloatingPlatform,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_input_keys: ["state"]
    normalize_value: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: transformer
    min_lr: 0
    base_lr: 3e-4
    warmup_steps: 15
    warmup_factor: 0.1
    kl_threshold: 0.016
    score_to_win: 20000
    max_epochs: ${resolve_default:1000,${....max_iterations}}
    save_best_after: 50
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 8192
    mini_epochs: 8
    critic_coef: 0.5
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
